spring:
  banner:
    location: classpath:banner/banner.txt
    image:
      location: classpath:banner/banner.gif
      width: 20

logging:
  level:
    org:
      springframework: info
      jline: error
    ru.otus.hw4.testingapp: error
    ru.otus.hw4.testingapp.service: info

testapp:
  csvPath: file:${DATACSV:.}
  globTemplate: "*.{csv}"
  separator: ","
  isCorrectSuffix: "\\ *\\* *$"
